- cafe
  - "AMALFI FRESH PASTA MALVERN EAST"
- coffee
  - "M-CITY CAFE 175754 OAKLEIGH EAST"
  - "STARBUCKS COFFEE MELBOURNE"
  - "Workshop Glenhuntly Glen Huntly VI"
  - "Workshop Glenhuntly Glen Huntly VI AUS Card xx2644 Value Date: 29/06/2025"
- entertainment
  - "GLEN HUNTLY NEWS & LOTT 1164 Glen Hun AU"
  - "GYMBAROO MALVERN        SOUTH MELBOURNE"
  - "HOYTS                   SYDNEY"
  - "NETFLIX MONTHLY"
  - "NETFLIX SUBSCRIPTION"
  - "SPOTIFY PREMIUM SUBSCRIPTION"
- food
  - "SQ *ETEN CARNEGIE Carnegie AU"
- food delivery
  - "UBER EATS HELP.UBER.COM"
- groceries
  - "BREADTOP CHADSTONE 2892 MALVERN EAST"
  - "COLONIAL FRUIT COMPANY CHADSTONE"
  - "FU XI ASIAN GROCERY     GLEN HUNTLY"
  - "FU YAO TRADING PTY LTD GLEN HUNTLY AU"
  - "HONG KONG ASIAN FOOD CLAYTON VI AUS Card xx2644 Value Date: 19/07/2025"
  - "Mitchells Quality Meats 359-365 Clayt AU"
  - "ORNOND FLOWERS Ormond"
  - "SHANGHAI SUPERMARKET CARNEGIE AUS Card xx2644 Value Date: 05/07/2025"
  - "SHANGHAI SUPERMARKET CARNEGIE VICAU"
  - "TEDDY BAKERY BRICKWORKS Burwood East"
  - "THE FOODIE SUPPLY SUPERAUHUGHESDALE AU"
  - "WOOLWORTHS 3133 CHADSTO CHADSTONE"
  - "WOOLWORTHS 3153 GLEN HU GLENHUNTLY"
- health
  - "CHEMIST WAREHOUSE KOORN CARNEGIE"
  - "Direct Debit 000187 CBHS 10134206"
  - "Direct Debit 000187 CBHS 10135104"
  - "TOP CARE MEDICAL CENTRE VERMONT"
- home improvement
  - "BUNNINGS WAREHOUSE 6438 OAKLEIGH SOUTH"
  - "IKEA AUSTRALIA          INNALOO"
- income
  - "Direct Credit 002221 MCARE BENEFITS 117097869 CYWQ"
  - "Direct Credit 002221 MCARE BENEFITS 122059442 CYWQ"
- mental health
  - "RAMSAY HEALTH CARE INV BOX HILL VI AUS Card xx2644 Value Date: 03/07/2025"
- online shopping
  - "AMAZON PURCHASE #456"
  - "AMAZON PURCHASE #789"
- pet
  - "GUILD INSURANCE LIMI MELBOURNE AUS Card xx8806 Value Date: 15/07/2025"
  - "PETBARN CAULFIELD       CAULFIELD SOUTH"
  - "PETSTOCK PTY LTD        ORMOND"
  - "ZLR*POPPET ACADEMY POPP BLACKBURN"
- refreshments
  - "GONG CHA THE GLEN 15675 GLEN WAVERLEY"
  - "HEYTEA CLAYTON 182590 CLAYTON"
  - "MORK CHOCOLATE ELEVATOR Melbourne"
  - "SHARETEA LILYDALE       Brighton East"
  - "YO- CHI SOUTHLAND 29675 CHELTENHAM"
  - "YO-BAR 181853           CHADSTONE"
  - "Yo- Chi SouthLand Cheltenham AU"
- restaurant
  - "GOLDEN BOWL CLAYTON PT Clayton VI AUS Card xx2644 Value Date: 27/06/2025"
  - "IPPUDO - CHADSTONE CHADSTONE"
  - "Kaiten Sushi Chadstone"
  - "LS BAMI SOUTHLAND       CHELTENHAM"
  - "MCDONALD'S 0401 ORMOND"
  - "MCDONALDS ELIZABETH STR MELBOURNE"
  - "MCDONALDS ORMOND 0401 ORMOND"
  - "NENE CHICKEN            CLAYTON"
  - "OrderBuddy_AFP Clayton AU"
  - "Qiqihar Charc Caulfield Eas VI AUS Card xx2644 Value Date: 28/06/2025"
  - "Subway Glenhuntly 1225 GlenhuntAU"
  - "THE HOT BIRD - CARNEGIE Glen Iris"
  - "TS/MARRYBROWN BURWOOD VICTORIA"
  - "WINDCAVE*NEW SHANGHAI C CHADSTONE"
- service
  - "IN VOGUE (PAPILLON) DRY CAULFIELD SOUTH"
  - "JOE & SIM PHOTO BOOTH PTYKeysborough AU"
  - "NAYAXAU*JOE  SIM PHOTO  KEYSBOROUGH"
  - "PROPOOL.COM.AU MOORABBIN"
  - "Transfer To Xiong J CommBank App Aimee"
- shopping
  - "AMAZON AU SYDNEY SOUTH"
  - "AMAZON MARKETPLACE AU SYDNEY SOUTH"
  - "Chadstone S813260       MalvernEast"
  - "David Jones Burnley AU AUS Card xx2644 Value Date: 16/07/2025"
  - "LUSH AUSTRALASIA RETAIL VILLAWOOD"
  - "NEW MERCHANT"
  - "PASPALEY CHADSTONE CHADSTONE"
  - "TOYMATE SOUTHLAND 28985 CHELTENHAM"
- subscription
  - "1PASSWORD               TORONTO"
  - "AMZNPRIMEAU MEMBERSHIP SYDNEY SOUTH"
  - "GOOGLE *YOUTUBEPREMIUM G.CO/HELPPAY#"
  - "RING STANDARD PLAN HAWTHORNE"
- transport
  - "Direct Debit 317213 myki-tnfr08AUG25 DE2D208518"
  - "UBER *EATS HELP.UBER.C Sydney AU AUS Card xx8806 Value Date: 03/07/2025"
- utilities
  - "APPLE.COM/BILL SYDNEY"
  - "JB HIFI MOBILE          MELBOURNE"
  - "TELSTRA CORPORATION LIM MELBOURNE"
